[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "tfg-pqc"
version = "0.1.0"
description = "Post-Quantum Cryptography and ECH latency measurement project"
requires-python = ">=3.9"
dependencies = [
    "tqdm",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scipy",
    "statsmodels",
    "dnspython",
    "cryptography",
    "scikit-learn",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]
